
server:
  port: 8089
  shutdown: graceful
spring:
  profiles:
    active: dev
  application:
    name: xf-boot-base
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      FAIL_ON_EMPTY_BEANS: false



mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    auto-mapping-behavior: full
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启SQL语句打印
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      update-strategy: IGNORED
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0

# 参考文章  https://zhuanlan.zhihu.com/p/145359625
management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      show-details: always

# 日志设置
logging:
  level:
    root: