#spring:
#  datasource:
#    dynamic:
#      primary: master
#      strict: true #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
#      hikari:
#        minimum-idle: 4
#        maximum-pool-size: 4
#        connection-init-sql: SELECT 1
#        connection-test-query: SELECT 1
#      datasource:
#        master:
#          url: jdbc:mysql://rm-2vcg431j388xlt5541o.mysql.cn-chengdu.rds.aliyuncs.com:3306/nearby_travel?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
#          username: aliyun_test
#          password: testRootZby!2020@
#          driver-class-name: com.mysql.cj.jdbc.Driver
#        slave:
#          url: jdbc:mysql://rm-2vcg431j388xlt5541o.mysql.cn-chengdu.rds.aliyuncs.com:3306/nearby_travel?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
#          username: aliyun_test
#          password: testRootZby!2020@
#          driver-class-name: com.mysql.cj.jdbc.Driver
#  cloud:
#    config:
#      enabled: false
#    consul:
#      host: 192.168.10.111 #139.224.207.104
#      port: 8500
#      config:
#        # 是否启用配置中心，默认值 true 开启
#        enabled: false
#      discovery:
#        register: false # 是否需要注册
#grpc:
#  client:
#    GLOBAL:
#      security:
#        enable-keep-alive: true
#      keep-alive-without-calls: true
#      negotiation-type: plaintext
#    center-merchant:
#      address: 'discovery:///center-merchant'
#      # kdm 192.168.11.116
#      # gsj 192.168.10.43
#      # tc 192.168.9.62
#      #      address: 'static://192.168.11.116:9999'
#      enableKeepAlive: true
#      keepAliveWithoutCalls: true
#    center-user:
#      address: 'discovery:///center-user'
#      #      address: 'static://192.168.10.43:8888'
#      enableKeepAlive: true
#      keepAliveWithoutCalls: true
#    center-ocr:
#      address: 'discovery:///center-merchant'
#      #      address: 'static://192.168.10.43:6566'
#      enableKeepAlive: true
#      keepAliveWithoutCalls: true
#    center-contract:
#      address: 'discovery:///center-contract'
#      enableKeepAlive: true
#      keepAliveWithoutCalls: true
#    center-dataapi:
#      address: 'static://192.168.8.126:9999'
#      enableKeepAlive: true
#      keepAliveWithoutCalls: true
#
#
##redis
#redis:
#  dynamic:
#    datasource:
#      token:
#        database: 1
#        host: 192.168.10.113
#        port: 6379
#        password: '123456'
#        lettuce:
#          pool:
#            max-active: 8
#            max-wait: -1ms
#            max-idle: 8
#            min-idle: 0
#        timeout: 3000ms
#      res:
#        database: 0
#        host: 192.168.10.113
#        port: 6379
#        password: '123456'
#        lettuce:
#          pool:
#            max-active: 8
#            max-wait: -1ms
#            max-idle: 8
#            min-idle: 0
#        timeout: 3000ms
#oss:
#  name: alioss
#  endpoint: ll-oss-pre.lianlianlvyou.com
#  accessKey:
#  secretKey:
#  bucketName:
#  args:
#    expireTime: 3600 #过期时间
#    contentLengthRange: 2000 #大小限制
##oss:
##  name: alioss
##  endpoint: ll-oss-pre.lianlianlvyou.com
##  accessKey:
##  secretKey:
##  bucketName:
##  args:
##    expireTime: 3600 #过期时间
##    contentLengthRange: 2000 #大小限制
## redis分布式锁
#redisson:
#  enabled: true
#  address: 'redis://192.168.10.113:6379'
#  password: '123456'
#  database: 5
#  connectionPoolSize: 4
#  connectionMinimumIdleSize: 4
#
## 阿里云rocketmq
#aliyun:
#  rocketmq:
#    config:
#      AccessKey: 1
#      SecretKey: 1
#      NAMESRV_ADDR: 1
#      GROUP_ID: 1
#    producer:
#      enabled: true
#
#rabbitmq:
#  configs:
#    order: #实例名称
#      host: 192.168.10.111
#      port: 5672
#      virtualHost: ll-dev
#      username: zhangziheng
#      password: zhangziheng
#      producer:
#        enabled: true
#        exchange: order_status
#        routingKey: ORDER_COMPLETE
#        confirmCallback: orderMqConfirmCallback
#    commonChange:
#      host: 192.168.10.111
#      port: 5672
#      virtualHost: ll-dev
#      username: zhangziheng
#      password: zhangziheng
#      producer:
#        enabled: false
#      consumer:
#        enabled: true
#        subscribeList:
#          - queue: 'app-business'
#            messageListener: commonChangeMessageListener
#
##应用可以默认使用的配置文件
#global:
#  testCofnig: "aaa"
#  tokenSecret: '12435twefdsfsdt4tsdcqw43tregdsgd'
#  tokenExpire: 14400 #10天
#  smsMqTopic: 'topic_msg'
#  smsMqTag: 'tag-sms'
#  rsaPrivateKey: 'MIIEpQIBAAKCAQEAuAltXJI4kMQkucWCeLGK4Zyqw7VUp1JYS1GkJb0eJKCgxqJBzwjl8XpStA1hCv9BEX6SEsm/d2T6SDo+G6ySpfV0RQeZ7v32kE9+Eh0BK1Q8wU91nCa1CM9yfBhKXsQ3DKq2am5oLryNWXdKLXZPgoJbuIONG2G4oKakwUMX3aASp3Cj3rNXLea8ilXjFZ+OEp0DuZ4CsasO1MTaBS84mJhnzRNbuhHq5qyrVI02jw7Fim8siIBsmDDHgBd4l9hj6KAAr0jf9JOHaOp+KxfH76taqqaXI5lZIPG7lCP65iBuNNEqDSc21abcPhgvgK5K4xj9p5sG+V1FBISCE0dPrQIDAQABAoIBAG6dg/UTEhq5OhXKyDwBAqfOgbk2IVacoONMg+wG+rorLdeWKRXmlEcLLfB45i409Agu2l+ekY2SzPhiwXfixxYnLSZchkJmtS9SCEWc11oSvJ24Q8mCXmeYQIikFPdW2nurlA7uo4IL5K20jIo8xVd9QOHreAHQP6eX4gkjaZHUIOSJ2P6iffEQCHbXehoyCoTMLdK+1HTuZdO4C9r/S9f/Y1kLWfV5ogEi0DHJpUy37npinfqPp0LHbgpK2WBPOkQIhKvi/4OQ71EcYR5gyrA7nR+rQyPHdhFzTTyfTNTgmuNFuAYJODN5yd62RQd8i6chMx63tYDoYhCjI/ixv8UCgYEA9S1JTacLrFQP+2ryHnn6A3JOhbzj1Y552Nc1XixI9aJMxxCJGI0PvmzDb46BSLfoOz4yaqL1lBS2vyX4tc1rKL82JiokZhDlnFNS0yQgR03484BGPJ3D1+tTWQV0cXyq0nYOI+m9vPBciI1Lw07tJ5ZqJbTabtcu2aq8WrKMuFsCgYEAwCk0WB5TTQJQgjuuFXT/GU4cIl8/Pa3IgF7Ccd1WVkFr9uI6vBpToN+0i1zAb83Ss9maD3eH1Na/7GiKwzZOJj8Yas6b1UsbcHZA1Yt+cI2WUZf8L8QVYJrUtIkbKbG+jdg/KjjZt8mAO8IcXivUhfmj8XUIBClYCezEZmSIVpcCgYEAupHWmUfHo0Bo1QqB6l0pupuuUyj1OxprcG38B4itkHYL9OOJX+xgEalUYzzO9tYz23kuBmWxeRj2I6kyhK4noF85RnuFLUIoZ/gkK9Xu1jPogOuZByGK2XETAMgc3wteNj9t7Tg+kVtbHvJet+YEo75bUgw4uGX5GdxJ7r62RMcCgYEAgJfSaJm6oxFGcTCg+cj2oaeM2k+lEZCHWaiQNQSqr0ROjMOuDI0No92wg4aJXQh+1U5sc6dI5dzkSL9ZBPQFbkDRBUDINf9yGFt6Xa1g6s9FZcrwv8JXj/NtHneWDtvcqi2pb4bl48DbqKHou/hW22VJGd94gthsCxBACkmCl3cCgYEAp2/KJrDnLwAr4h6SVCufRRuNkZSRI+XITkE4xyQ/UDeL+iwCbX38Jcqa2lxCAXCLk++1xilSF/sJbBVkiDorBU9CC0tI5tPJFfHQodbePx1C0SQE8e0F+wtaeR9Z5m5KzHNs2Gciqw+2nJPU9uFQjUfGdXuIZF2bBvtXBWH+Prk='
#  rsaPublickey: 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuAltXJI4kMQkucWCeLGK4Zyqw7VUp1JYS1GkJb0eJKCgxqJBzwjl8XpStA1hCv9BEX6SEsm/d2T6SDo+G6ySpfV0RQeZ7v32kE9+Eh0BK1Q8wU91nCa1CM9yfBhKXsQ3DKq2am5oLryNWXdKLXZPgoJbuIONG2G4oKakwUMX3aASp3Cj3rNXLea8ilXjFZ+OEp0DuZ4CsasO1MTaBS84mJhnzRNbuhHq5qyrVI02jw7Fim8siIBsmDDHgBd4l9hj6KAAr0jf9JOHaOp+KxfH76taqqaXI5lZIPG7lCP65iBuNNEqDSc21abcPhgvgK5K4xj9p5sG+V1FBISCE0dPrQIDAQAB'
#  appDowloadUrl: 'http://llzby.cn/s/E9TTlQrJ'
#  pcAccessUrl: 'http://llzby.cn/s/E9TTlQrJ'
#  customServiceUrl: 'https://chaten.soboten.com/chat/h5/v2/index.html?sysnum=caf21f78c499463fbb54077f5c4a8efd&channelid=13&source=1&groupid=d16ef9bdcf3b46dc9726bbb00a7ee45b&partnerid=' #智齿客服 + biz_userId
#
#merchant:
#  personAuth-callback: http://lianlian.free.idcfengye.com/center/callback/personAuth/
#  enterpriseAuth-callback: http://lianlian.free.idcfengye.com/center/callback/enterpriseAuth/
#consume:
#  third: http://lianlian.free.idcfengye.com/ll/api/order/internal/consumeOrder
#  douyin: http://127.0.0.1:8080/ll/byteDance/pay/order/writeOff
#protocol:
#  user: https://debug.lianlianlvyou.com/businessapp/user-service-protocal.html # 用户服务协议
#  privacy: https://debug.lianlianlvyou.com/businessapp/user-privacy-protocal.html # 用户隐私协议
#guest:
#  username: 18483679330 #游客 用户名
#  password: 123456 #游客 密码
#  merchantId: 402936
#amap:
#  key: 9e04c876425e1f9879e941ed6db8d9c4 #高德地图key
#  poiDetailUrl: https://restapi.amap.com/v3/place/detail # 详情url
#withdraw:
#  termUrl: https://oasd.lianlianlvyou.com/finance/open/periodic # 周期性核销结款
#  termSpecialUrl: https://oasd.lianlianlvyou.com/finance/open/periodic/new # 周期性核销结款
#  preUrl: https://oasd.lianlianlvyou.com/finance/open/advance # 预付款
#  calc: https://oasd.lianlianlvyou.com/finance/open/apply/data/treasure #计算合同可提现
#bankUrl:
#  branchName: https://oasd.lianlianlvyou.com/finance/open/search/bank/deposit #查询支行名称 GET bankName = ?
#
